
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const LOAD_PRODUCT ="LOAD_PRODUCT"
export const ADD_PRODUCT= "ADD_PRODUCT"
export const REMOVE_PRODUCT= "REMOVE_PRODUCT"
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"

// for filter 

export const TOGGLE_BRANDS= "TOGGLE_BRANDS"
export const TOGGLE_STOCK= "TOGGLE_STOCK"